//SYNC
export const types = {
    FILL_POSTS: 'FILL_POSTS',
    FETCH_POSTS: 'FETCH_POSTS',
    CREATE_POST: 'CREATE_POST',
    CLEAR_POSTS: 'CLEAR_POSTS',
    REMOVE_POST: 'REMOVE_POST',

    REMOVE_POST_ASYNC: 'REMOVE_POST_ASYNC',
    CREATE_POST_ASYNC: 'CREATE_POST_ASYNC',
};
